2024-10-21 19:40:44,859 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "E:\python\project\lession\module_12\test_12_4.py", line 25, in test_run
    tr = Runner(2)
         ^^^^^^^^^
  File "E:\python\project\lession\module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-21 19:40:44,860 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "E:\python\project\lession\module_12\test_12_4.py", line 14, in test_walk
    tw = Runner('Test1', speed=-2)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\project\lession\module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -2
